# Uso de imagen base pesada (Python estándar)
FROM python:3.11

# Directorio de trabajo
WORKDIR /app

# Copiar requerimientos e instalar
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiar el código de la app
COPY app/ ./app/

# Exponer el puerto único
EXPOSE 6969

# Comando de ejecución
CMD ["python", "app/main.py"]